opam
New version of Core makes ppx_deriving optional. This breaks ocaml-ipaddr.
=> add ppx_deriving dependency

ipaddr.opam
This is used directly so we shouldn't rely on ppx_sexp_conv to pull it
transitively.
A point release with this chnage would be appreciated.
=> Add sexplib dependency to opam

lib/macaddr.ml
The warning for the pattern match on `Invalid_argument` complains that it is not kosher to rely on the string argument for differentiation between errors.
If people would prefer a guard before the `Char.chr` I can add that to this PR instead.
=> macaddr: try to make it spit out fewer errors while compiling

.gitignore, .travis.yml, CHANGES.md, Makefile, README.md, dune-project, ipaddr.opam, lib/dune, lib/ipaddr.ml, lib/ipaddr.mli, lib/ipaddr_sexp.ml, lib/ipaddr_sexp.mli, lib/macaddr.ml, lib/macaddr.mli, lib/macaddr_sexp.ml, lib/macaddr_sexp.mli, lib/macaddr_top.ml, lib_test/dune, lib_test/test_ipaddr.ml, lib_test/test_macaddr.ml, lib_test/test_ppx.ml, macaddr.opam
Just still finishing this of but wanted to preview the PR. This release features several backwards incompatible changes, but ones that should increase the portability and robustness of the library.  Requested by @hannesm for smaller unikernels.
=> [wip] rel 3.0.0 with soft sexp dependency and result types

lib/ipaddr.ml, lib/ipaddr.mli
was not used, is confusing. the RFC 5952 recommends to output v4-mapped
addresses as ::ffff:192.168.0.1, which is done nicely by the code.
I searched github, and only https://github.com/mirage/ocaml-tuntap/blob/master/test/getifaddrs_test.ml#L12 uses this, supplying `false`, the default. see https://github.com/mirage/ocaml-tuntap/pull/29 for removing it there :)
=> Ipaddr.V6.to_string, to_buffer: remove optional labeled argument `v4`

ipaddr-sexp.opam, ipaddr.opam, lib/dune, lib_test/dune, macaddr-sexp.opam
Moves `Ipaddr_sexp` and `Macaddr_sexp` to their own opam packages.
I had to use the same hack as https://github.com/mirage/ocaml-uri/pull/134 to make `dune-release` happy. Is there a cleaner way ?
=> ipaddr-sexp and macaddr-sexp

ipaddr.opam, lib/dune, lib/ipaddr.ml, lib/ipaddr.mli, lib_test/test_ipaddr.ml
=> use domain-name library to produce domain names from ip addresses

CHANGES.md, lib/ipaddr.ml, lib/ipaddr.mli, lib/macaddr.ml, lib/macaddr.mli, lib_test/test_ipaddr.ml, lib_test/test_macaddr.ml
Rename the `to/from_bytes` functions to refer to `octets` instead.  This distinguishes the meaning of human-readable addresses (`string`s in this library) and byte-packed representations(`octet`s in this library) from the OCaml `bytes` type that represents mutable strings.
Porting code should just be a matter of renaming functions such as:
- `Ipaddr.of_bytes` becomes `Ipaddr.of_octets`
- `Macaddr.to_bytes_raw` becomes `Macaddr.to_octets_raw` and so on.
=> Rename bytes functions to octets instead

.travis.yml, CHANGES.md, dune-project, ipaddr-cstruct.opam, ipaddr-sexp.opam, lib/dune, lib/ipaddr_cstruct.ml, lib/ipaddr_cstruct.mli, lib/macaddr_cstruct.ml, lib/macaddr_cstruct.mli, lib_test/dune, lib_test/test_ipaddr.ml, lib_test/test_macaddr.ml, macaddr-cstruct.opam
for conversion to/from cstructs
based on #36
Co-authored-by: Nicolás Ojeda Bär <n.oje.bar@gmail.com>
=> Add new `Ipaddr_cstruct` and `Macaddr_cstruct` libraries

ipaddr-cstruct.opam, ipaddr-sexp.opam, ipaddr.opam, macaddr-cstruct.opam, macaddr-sexp.opam, macaddr.opam
This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.
=> opam: remove the 'build' directive on dune dependency

CHANGES.md, ipaddr.opam, lib/ipaddr.ml, lib/ipaddr.mli, lib_test/test_ipaddr.ml
while trying to use ipaddr 4.0.0, I discovered that the Prefix.of_netmask functions are in a slightly sad state:
- they raise exceptions
- they get two arguments of type addr -- and I always get the order wrong
so I instead:
- changed the signature of of_netmask : netmask:addr -> address:addr -> (t, msg) result
- provided a of_netmask_exn, which value is t
~~in a separate commit I use stdlib-shims to have this compile without warnings on newer OCaml compilers~~. also, remove the `sexplib0` dependency from ipaddr.opam. I know this breaks the API again, but only for some users ;) -- and better to have it coherent now than to embed the boilerplate to get a result from of_netmask in all the clients.
=> Prefix.of_netmask: avoid exceptions, provide of_netmask_exn

lib/ipaddr.ml, lib_test/test_ipaddr.ml
Fixes #97 
V4.Prefix.mem returns false when testing an IPv4 address for inclusion in 0.0.0.0/0. This only happens in the toplevel or when compiling to bytecode. The root cause could be that the function uses shift_right_logical, whose behavior is undefined for values of 32 for example. This happens for prefix length of 0, where 32 is used as an argument when calling shift_right_logical.
=> V4 mem fix

lib/ipaddr.ml, lib/ipaddr.mli, lib/ipaddr_sexp.ml, lib/ipaddr_sexp.mli, lib_test/dune, lib_test/test_ipaddr.ml, lib_test/test_ipaddr_b128.ml, lib_test/test_ppx.ml
Hi there! I think these improvements would be useful not only for me.
- added forgotten `Ipaddr_sexp.Prefix` module
- for `Ipaddr`, `Ipaddr.V4` and `Ipaddr.V6` added functions `succ` and `pred` to get next and previous addresses
- for `Ipaddr.Prefix`, `Ipaddr.V4.Prefix` and `Ipaddr.V6.Prefix` added functions `first` and `last` to get first and last valid unicast addresses in subnet
=> Utility functions

lib/ipaddr.ml, lib_test/test_ipaddr.ml
Based on a recent CVE, I propose a patch to reject the use of octal notation in IPv4.
See some related information here:
https://www.bleepingcomputer.com/news/security/python-also-impacted-by-critical-ip-address-validation-vulnerability/
=> reject octal notation in ivp4

ipaddr-cstruct.opam, lib/ipaddr.ml, lib/ipaddr.mli, lib/ipaddr_cstruct.ml, lib/macaddr_cstruct.ml, lib_test/test_ipaddr.ml, macaddr-cstruct.opam
This is a request for comments about extending the interface: I struggled in [happy-eyeballs](https://github.com/roburio/happy-eyeballs) which needs a Set of IPv4/IPv6 addresses and [dns](https://github.com/mirage/ocaml-dns) which uses these sets as well. Now, happy-eyeballs should be used in the dns resolver (and thus best to not have a dependency between happy-eyeballs and dns).
So, if anyone (@dinosaure @avsm anyone else from @mirage/core) has arguments to not provide the Set and Map submodules, please comment in this PR. Otherwise, I'll merge next week and cut a release to rebase happy-eyeballs and dns on top of these modules.
=> Fixes: cstruct 6.0.0 and Set and Map

lib/ipaddr.ml, lib/ipaddr.mli, lib_test/test_ipaddr.ml
/cc @hannesm. Unfortunately, the parsing is much more harder than expected due to the _best-effort_ behavior. Indeed, `Ipaddr.of_string "127.0.0.1aaaa"` is correct and I tried to keep such behavior with `Ipaddr.with_port_of_string ~default:80 "127.0.0.1:8080aaaa"`. Tests clarify a bit this situation with a check that `with_port_of_string` has the same result than `{V4,V6}.with_port_of_string` according to the result.
=> Add *.with_port_of_string functions

ipaddr-cstruct.opam, ipaddr-sexp.opam, ipaddr.opam, lib/dune, macaddr-cstruct.opam, macaddr-sexp.opam, macaddr.opam
See https://github.com/mirage/ocaml-cstruct/pull/298 for a similar discussion. With OCaml 5.00 on the horizon, I'm keen to drop support for arcane OCaml releases, and minimize the dependency cone (also see https://discuss.ocaml.org/t/lwt-informal-user-survey/9666 which may drop < 4.08 for lwt).
=> remove stdlib-shims dependency, require OCaml 4.08

.ocamlformat, lib/ipaddr.ml, lib_test/test_ipaddr.ml, lib_test/test_ipaddr_b128.ml
* this PR is a proposal to addresses issue #16
* I didn't touch any parsing functions, but migrated auxiliary functions to operate on Bytes. If this was over the top, I could cut this PR down to the essential parts and keep the rest for later.
* I've resorted to imperative code due to the index based set functions of Bytes
=> use Bytes.t as data type for IPv6 addresses

lib/ipaddr.ml, lib/ipaddr.mli, lib_test/test_ipaddr.ml
This PR adds host and subnet iterators to the V4/V6.Prefix modules. At the moment, the implementation of the IPv6 subnet iterator is missing, hence the WIP. But I wanted to open the PR to get some feedback, especially regarding exceptions and the code in general.
Currently, invalid parameters to the subnets function just return a Seq.Nil instead of an exception. I didn't want
to wrap them into options or results, which would be a bit heavier to unpack for the users of the library.
But maybe raising an exception for arguments that are clearly out of bounds, like a prefix length bellow 0
or above 32 for IPv4 for example would be fine.
The implementation mimics the behavior of the methods in Python's ipaddress module.
I haven't exposed the hostmask functions in the signature, because I …
=> add host and subnet Seq.t iterators to V4/V6.Prefix

lib/ipaddr.ml
Int32.unsigned_compare has been available since OCaml 4.08. Since this is the lower bound anyway we might as well use it instead of reimplementing it ourselves.
=> V4.compare: use Int32.unsigned_compare

lib/ipaddr.ml, lib/ipaddr_cstruct.ml, lib_test/test_ipaddr.ml, lib_test/test_ipaddr_b128.ml
The interface of `B128` introduced in #115  is functional in that the arguments to its functions are not mutated. This PR replaces `B128` with a module `S128` that internally uses `Bytes.t` but externally operates on `string`s. Furhermore, 
- the type `S128.t` is made abstract with a signature for `S128`,
- some functions only used in tests are moved to the relevant tests, and
- `sub_exn` is replaced by `pred_exn` as the only usage of `sub_exn` was subtracting one.
=> Use string for 128 bit integers (IPv6 addresses)

lib/ipaddr.ml, lib/ipaddr.mli
previously only Ipaddr.V4.Prefix.address and Ipaddr.V6.Prefix.address were available. it is pretty useful to also extract an IP address from an Ipaddr.Prefix.t
=> add Ipaddr.Prefix.address
